version: "3.8"

services:
  postgres:
    image: "postgres"
    ports:
      - 49153:49153
    environment:
      POSTGRES_PASSWORD: postgrespw # Make sure to use your own!
      POSTGRES_DB: ecomm
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"

      